name: Full React CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  # 1️⃣ Checkout & Setup
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  # 2️⃣ Install Dependencies
  install:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend-app
          npm install

  # 3️⃣ Static Code Analysis
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run ESLint
        run: |
          cd frontend-app
          npm install
          npx eslint src || true

  # 4️⃣ Security Scan (Bandit - simulated)
  security:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Bandit scan
        run: |
          pip install bandit
          bandit -r . || true

  # 5️⃣ Unit Tests
  test:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run unit tests
        run: |
          cd frontend-app
          npm install
          CI=true npm test

  # 6️⃣ Trivy Filesystem Scan (Before Docker)
  trivy-fs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: frontend-app
          severity: HIGH,CRITICAL

  # 7️⃣ Docker Build + 8️⃣ Trivy Image Scan
  docker-build-scan:
    needs: trivy-fs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd frontend-app
          docker build -t simple-react-app:latest .

      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: simple-react-app:latest
          severity: HIGH,CRITICAL

